# SPDX-FileCopyrightText: 2022 Agency for Digital Government
#
# SPDX-License-Identifier: EUPL-1.2

spring.application.name=dcat-ap-se-processor

apitype.R10=RAML 1.0
apitype.O30j=OAS 3.0 json
apitype.O30y=OAS 3.0 yaml
apitype.json=JSON metadata

dcat.specification.properties=dcat_specification.properties

# Health metrics
management.endpoints.web.exposure.include=health,prometheus
management.metrics.tags.application=${spring.application.name}