# SPDX-FileCopyrightText: 2022 Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

name: Maven Test

on: [workflow_call]

permissions:
  contents: read

jobs:
  test:
    name: maven-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        java-version: ["25"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
          cache: "maven"

      - name: Run tests
        env:
          MAVEN_CLI_OPTS: --batch-mode --no-transfer-progress --errors --fail-at-end -Dstyle.color=always -DinstallAtEnd=true -DdeployAtEnd=true
          GITHUB_ACTOR: ${{ github.actor }}
          PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # shellcheck disable=SC2086
          mvn $MAVEN_CLI_OPTS test
