# SPDX-FileCopyrightText: 2022 Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

name: Maven Test

on: [workflow_call]

permissions:
  contents: read

jobs:
  test:
    name: maven-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        java-version: ["25"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
          cache: "maven"

      - name: Run tests
        env:
          MAVEN_CLI_OPTS: --batch-mode --no-transfer-progress --errors --fail-at-end -Dstyle.color=always -DinstallAtEnd=true -DdeployAtEnd=true
          GITHUB_ACTOR: ${{ github.actor }}
          PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # shellcheck disable=SC2086
          mvn $MAVEN_CLI_OPTS test
